### ISSUE TITLE
CONSULTA NFE SEFAZ DIFERENTE DO DF.

### ISSUE THREAD

**Issue by skerme** [lucashpmelo/node-mde#12]
### Descrição

Sou iniciante no mundo web e como projeto pessoal decidi fazer um sistema que consulta as notas de um cnpj num período e totaliza o gasto.
Mas eu não sei nada disso. Tudo que aprendi foi a partir desse código aqui.

Repositósio do projeto com as alterações:  https://github.com/skerme/consultarSefazAmClone.git

meu email: skerme@gmail.com
zap: 92 981861396

Desde já agradeço.

ALTERAÇÕES:

DISTRIBUIÇÃO.JS
     1: 'https://nfe.sefaz.am.gov.br/services2/services/NfeConsultaNFe?wsdl', 

distribuicaoDFe-helper.js
       method: 'GET',

INDEX.JS

 //const { DistribuicaoDFe } = require('node-mde')
console.log("RESULTADO: ", funcao())
async function funcao(){

  const fs = require('fs')

  const distribuicao = new DistribuicaoDFe({
    pfx: fs.readFileSync('./sabor.pfx'),
    passphrase: 'Sabor2022',
    cnpj: '48327424000191',
    cUFAutor: '41',
    tpAmb: '1',
  })
  
  const consulta = await distribuicao.consultaChNFe(
    '13230734550453000103550010000026821098620239'
  )
  
  if (consulta.error) {
    throw new Error(consulta.error)
  }
  
  console.log(consulta)
}

**Comment by lucashpmelo** [comment]
Boa noite, essa biblioteca faz a comunicação com os Web Services do Ambiente Nacional da Sefaz, o de **Distribuição de DF-e** e o **Recepção de Evento**, esses dois Web Services não são específicos de cada estado.

Pelo o que eu entendi você quer consultar Notas Fiscais no estado do Amazonas, nesse caso você deve passar o código do estado correto na propriedade de `cUFAutor`, que no caso do Amazonas seria o `'13'`.


``` js
const { DistribuicaoDFe } = require("node-mde");
const fs = require("fs");

async function funcao() {
  const distribuicao = new DistribuicaoDFe({
    pfx: fs.readFileSync("./sabor.pfx"),
    passphrase: "Sabor2022",
    cnpj: "48327424000191",
    cUFAutor: "13", // <-- Código do estado do Amazonas
    tpAmb: "1",
  });

  const consulta = await distribuicao.consultaChNFe(
    "13230734550453000103550010000026821098620239"
  );

  if (consulta.error) {
    throw new Error(consulta.error);
  }

  console.log(consulta);
}

console.log("RESULTADO: ", funcao());
```

Na documentação possui uma tabela com os [códigos de cada estado](https://github.com/lucashpmelo/node-mde#c%C3%B3digos-uf).

**Comment by skerme** [comment]
Olá, em outra tentativas já tinha mudado para 13 a respostas continua a
mesma. Eu acabo de fazer neste instante.

Em dom., 8 de out. de 2023 às 19:49, Lucas Melo ***@***.***>
escreveu:

**Comment by skerme** [comment]
Será que tenho que mudar o timezone para  America/Manaus em algum dos
arquivos?

Em dom., 8 de out. de 2023 às 19:57, skerme ***@***.***> escreveu:

**Comment by lucashpmelo** [comment]
> Olá, em outra tentativas já tinha mudado para 13 a respostas continua a mesma.

Coloque qual é mensagem de retorno por favor. Assim eu consigo saber se é um erro ou uma mensagem da Sefaz.

> Será que tenho que mudar o timezone para  America/Manaus em algum dos arquivos?

Isso seria apenas na emissão de Evento de Manifestação.

**Comment by skerme** [comment]
node index.js
RESULTADO:  Promise { <pending> }
{
  data: {
    tpAmb: '',
    verAplic: '',
    cStat: '',
    xMotivo: '',
    dhResp: '',
    ultNSU: '',
    maxNSU: '',
    docZip: []
  },
  reqXml: '<?xml version="1.0" encoding="utf-8"?><soap12:Envelope
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="
http://www.w3.org/2001/XMLSchema" xmlns:soap12="
http://www.w3.org/2003/05/soap-envelope"><soap12:Body><nfeDistDFeInteresse
xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe"><nfeDadosMsg><distDFeInt
xmlns="http://www.portalfiscal.inf.br/nfe"
versao="1.01"><tpAmb>1</tpAmb><cUFAutor>13</cUFAutor><CNPJ>48327424000191</CNPJ><consChNFe><chNFe>13230734550453000103550010000026821098620239</chNFe></consChNFe></distDFeInt></nfeDadosMsg></nfeDistDFeInteresse></soap12:Body></soap12:Envelope>',
  resXml: '<wsdl:definitions\n' +
    '    \n' +
    '     targetNamespace="
http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsultaNFe"\n' +
    '     xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"\n' +
    '     xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"\n' +
    '     xmlns:s="http://www.w3.org/2001/XMLSchema"\n' +
    '     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"\n' +
    '     xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"\n' +
    '     xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"\n' +
    '     xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"\n' +
    '     xmlns:tns="http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsultaNFe"\n'
+
    '     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"\n' +
    '    >\n' +
    '    <wsdl:types>\n' +
    '        <s:schema elementFormDefault="qualified" targetNamespace="
http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsultaNFe">\n' +
    '            <s:element name="nfeDadosMsg">\n' +
    '                <s:complexType mixed="true">\n' +
    '                    <s:sequence>\n' +
    '                        <s:any/>\n' +
    '                    </s:sequence>\n' +
    '                </s:complexType>\n' +
    '            </s:element>\n' +
    '            <s:element name="nfeConsultaNFeLogResult">\n' +
    '                <s:complexType mixed="true">\n' +
    '                    <s:sequence>\n' +
    '                        <s:any/>\n' +
    '                    </s:sequence>\n' +
    '                </s:complexType>\n' +
    '            </s:element>\n' +
    '            <s:element name="nfeCabecMsg" type="tns:nfeCabecMsg"/>\n' +
    '            <s:complexType name="nfeCabecMsg">\n' +
    '                <s:sequence>\n' +
    '                    <s:element maxOccurs="1" minOccurs="0"
name="versaoDados" type="s:string"/>\n' +
    '                </s:sequence>\n' +
    '                <s:anyAttribute/>\n' +
    '            </s:complexType>\n' +
    '        </s:schema>\n' +
    '    </wsdl:types>\n' +
    '    <wsdl:message name="nfeConsultaNFeLogSoapIn">\n' +
    '        <wsdl:part name="nfeDadosMsg" element="tns:nfeDadosMsg"/>\n' +
    '    </wsdl:message>\n' +
    '    <wsdl:message name="nfeConsultaNFeLogSoapOut">\n' +
    '        <wsdl:part name="nfeConsultaNFeLogResult"
element="tns:nfeConsultaNFeLogResult"/>\n' +
    '    </wsdl:message>\n' +
    '    <wsdl:message name="nfeConsultaNFeLognfeCabecMsg">\n' +
    '        <wsdl:part name="nfeCabecMsg" element="tns:nfeCabecMsg"/>\n' +
    '    </wsdl:message>\n' +
    '    <wsdl:portType name="NfeConsultaNFeSoap">\n' +
    '        <wsdl:operation name="nfeConsultaNFeLog">\n' +
    '            <wsdl:input message="tns:nfeConsultaNFeLogSoapIn"/>\n' +
    '            <wsdl:output message="tns:nfeConsultaNFeLogSoapOut"/>\n' +
    '        </wsdl:operation>\n' +
    '    </wsdl:portType>\n' +
    '    <wsdl:binding name="NfeConsultaNFeSoap"
type="tns:NfeConsultaNFeSoap">\n' +
    '        <soap:binding
transport="http://schemas.xmlsoap.org/soap/http"/>\n'
+
    '        <wsdl:operation name="nfeConsultaNFeLog">\n' +
    '            <soap:operation style="document" soapAction="
http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsultaNFe/nfeConsultaNFeLog"/>\n'
+
    '            <wsdl:input>\n' +
    '                <soap:body use="literal"/>\n' +
    '                <soap:header
message="tns:nfeConsultaNFeLognfeCabecMsg" part="nfeCabecMsg"
use="literal"/>\n' +
    '            </wsdl:input>\n' +
    '            <wsdl:output>\n' +
    '                <soap:body use="literal"/>\n' +
    '                <soap:header
message="tns:nfeConsultaNFeLognfeCabecMsg" part="nfeCabecMsg"
use="literal"/>\n' +
    '            </wsdl:output>\n' +
    '        </wsdl:operation>\n' +
    '    </wsdl:binding>\n' +
    '    <wsdl:binding name="NfeConsultaNFeSoap12"
type="tns:NfeConsultaNFeSoap">\n' +
    '        <soap12:binding
transport="http://schemas.xmlsoap.org/soap/http"/>\n'
+
    '        <wsdl:operation name="nfeConsultaNFeLog">\n' +
    '            <soap12:operation style="document" soapAction="
http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsultaNFe/nfeConsultaNFeLog"\n'
+
    '                 soapActionRequired="false"/>\n' +
    '            <wsdl:input>\n' +
    '                <soap12:body use="literal"/>\n' +
    '                <soap12:header
message="tns:nfeConsultaNFeLognfeCabecMsg" part="nfeCabecMsg"
use="literal"/>\n' +
    '            </wsdl:input>\n' +
    '            <wsdl:output>\n' +
    '                <soap12:body use="literal"/>\n' +
    '                <soap12:header
message="tns:nfeConsultaNFeLognfeCabecMsg" part="nfeCabecMsg"
use="literal"/>\n' +
    '            </wsdl:output>\n' +
    '        </wsdl:operation>\n' +
    '    </wsdl:binding>\n' +
    '    <wsdl:service name="NfeConsultaNFe">\n' +
    '        <wsdl:port name="NfeConsultaNFeSoap12"
binding="tns:NfeConsultaNFeSoap12">\n' +
    '            <soap12:address location="
https://nfe.sefaz.am.gov.br/services2/services/NfeConsultaNFe"/>\n' +
    '        </wsdl:port>\n' +
    '    </wsdl:service>\n' +
    '</wsdl:definitions>\n',
  status: 200
}

Em dom., 8 de out. de 2023 às 19:58, Lucas Melo ***@***.***>
escreveu:

**Comment by skerme** [comment]
Se tiver interesse, o certifico e senha estão no projeto alterado.

https://github.com/skerme/consultarSefazAmClone.git

Em dom., 8 de out. de 2023 às 20:03, skerme ***@***.***> escreveu:

**Comment by lucashpmelo** [comment]
Você está utilizando a biblioteca ou está usando o código que você mesmo modificou? Pois pelo retorno parece que você está dando um `GET` no wsdl do Web Service.

> Se tiver interesse, o certifico e senha estão no projeto alterado.

Testando pela biblioteca tenho esse retorno, que diz que a nota já passou do período de 90 dias:

``` js
// {
//   data: {
//     tpAmb: '1',
//     verAplic: '1.6.2',
//     cStat: '632',
//     xMotivo: 'Rejeicao: Solicitacao fora de prazo, a NF-e nao esta mais disponivel para download',
//     dhResp: '2023-10-08T20:29:25-03:00',
//     ultNSU: '',
//     maxNSU: '',
//     docZip: []
//   },
//   reqXml: '<?xml version="1.0" encoding="utf-8"?><soap12:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"><soap12:Body><nfeDistDFeInteresse xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe"><nfeDadosMsg><distDFeInt xmlns="http://www.portalfiscal.inf.br/nfe" versao="1.01"><tpAmb>1</tpAmb><cUFAutor>13</cUFAutor><CNPJ>48327424000191</CNPJ><consChNFe><chNFe>13230734550453000103550010000026821098620239</chNFe></consChNFe></distDFeInt></nfeDadosMsg></nfeDistDFeInteresse></soap12:Body></soap12:Envelope>',
//   resXml: '<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><nfeDistDFeInteresseResponse xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe"><nfeDistDFeInteresseResult><retDistDFeInt xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" versao="1.01" xmlns="http://www.portalfiscal.inf.br/nfe"><tpAmb>1</tpAmb><verAplic>1.6.2</verAplic><cStat>632</cStat><xMotivo>Rejeicao: Solicitacao fora de prazo, a NF-e nao esta mais disponivel para download</xMotivo><dhResp>2023-10-08T20:29:25-03:00</dhResp></retDistDFeInt></nfeDistDFeInteresseResult></nfeDistDFeInteresseResponse></soap:Body></soap:Envelope>',
//   status: 200
// }
```

**Comment by skerme** [comment]
Eu só clonei teu código numa pasta vazia. Alterei esses pontos no PDF  e o
foi um deles.




[image: image.png]



se eu volto a botar POST aí como é no código original a resposta é essa
abaixo:

[image: image.png]










Em dom., 8 de out. de 2023 às 20:06, Lucas Melo ***@***.***>
escreveu:

**Comment by lucashpmelo** [comment]
As imagens que você anexou não carregaram. No caso tente instalar a biblioteca pelo `npm i node-mde` e teste utilizando esse código:

``` js
const { DistribuicaoDFe } = require("node-mde");
const fs = require("fs");

async function funcao() {
  const distribuicao = new DistribuicaoDFe({
    pfx: fs.readFileSync("./sabor.pfx"),
    passphrase: "Sabor2022",
    cnpj: "48327424000191",
    cUFAutor: "13", // <-- Código do estado do Amazonas
    tpAmb: "1",
  });

  const consulta = await distribuicao.consultaChNFe(
    "13230734550453000103550010000026821098620239"
  );

  if (consulta.error) {
    throw new Error(consulta.error);
  }

  console.log(consulta);
}

console.log("RESULTADO: ", funcao());
```

Depois poste os resultados.

**Comment by skerme** [comment]
Lembrando que neste momento a única alteração no código é a url-->  e o
código em index.js
executado: npm i node-mde

const DISTRIBUICAO = {
  1: '
https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?wsdl
',
  2: '
https://hom1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?wsdl
',
}


[image: image.png]

Em dom., 8 de out. de 2023 às 20:17, Lucas Melo ***@***.***>
escreveu:

**Comment by skerme** [comment]
A foto da url era essa : const DISTRIBUICAO = {
  1: 'https://nfe.sefaz.am.gov.br/services2/services/NfeConsultaNFe?wsdl',
//'
https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?wsdl
',
  2: '
https://hom1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?wsdl
',
}


Em dom., 8 de out. de 2023 às 20:26, skerme ***@***.***> escreveu:

**Comment by lucashpmelo** [comment]
Por que você está fazendo a modificação da URL? Essa ação não é necessária.

**Comment by skerme** [comment]
achei que tivesse que inserir a url da sefaz do am. Eu mandei email para
eles e me disseram que era  essa:  '
https://nfe.sefaz.am.gov.br/services2/services/NfeConsultaNFe?wsdl'


Acabo de executar com a url do seu código original e retornou isso:


[image: image.png]

Em dom., 8 de out. de 2023 às 20:25, Lucas Melo ***@***.***>
escreveu:

**Comment by skerme** [comment]
Consultei a nfe que estamos usando e ela está disponível no site nacional:

[image: image.png]

Em dom., 8 de out. de 2023 às 20:33, skerme ***@***.***> escreveu:

**Comment by lucashpmelo** [comment]
> achei que tivesse que inserir a url da sefaz do am. Eu mandei email para eles e me disseram que era  essa:

Esse seria outro Web Service, para consultar as notas emitidas por você, no caso dessa biblioteca ela busca  as notas

**Comment by skerme** [comment]
testei com uma segunda nota: 13230934550453000103550010000028781301508871

[image: image.png]



terceira nota: 13230706710613000360550010001054001456923518


[image: image.png]

Em dom., 8 de out. de 2023 às 20:34, skerme ***@***.***> escreveu:

**Comment by lucashpmelo** [comment]
>achei que tivesse que inserir a url da sefaz do am. Eu mandei email para eles e me disseram que era  essa:  '

Esse seria outro Web Service, para consultar Notas emitidas por você, essa biblioteca busca as notas emitidas contra o seu CNPJ.

>Acabo de executar com a url do seu código original e retornou isso:

No caso você está anexando as Fotos no email, mas eu não recebo elas aqui no Github, poste elas pela [Issue que abriu no Github](https://github.com/lucashpmelo/node-mde/issues/12)

> Consultei a nfe que estamos usando e ela está disponível no site nacional:

O Portal Nacional utiliza um serviço interno deles, então eles podem consultar notas mais antigas, os Web Service disponibilizados para o publico normalmente tem um período de consulta de no máximo 90 dias.

**Comment by skerme** [comment]
![image](https://github.com/lucashpmelo/node-mde/assets/66704465/c297866c-b4e3-4c47-b2e0-a4807c24034f)


nota:  13230734550453000103550010000026821098620239
emitida contra o cnpj usado no código em : 2023-07-04T09:47:56-03:00

**Comment by skerme** [comment]
![image](https://github.com/lucashpmelo/node-mde/assets/66704465/dd0d5af0-8875-4bd3-8253-733549360e66)
nota: 13230834550453000103550010000028331140906379

destinatário sou eu: 48327424000191

**Comment by lucashpmelo** [comment]
>nota: 13230734550453000103550010000026821098620239
emitida contra o cnpj usado no código em : 2023-07-04T09:47:56-03:00

Essa nota foi emitida a 96 dias, então não é mais possível consultar pelo Web Service

>nota: 13230834550453000103550010000028331140906379
destinatário sou eu: 48327424000191

Essa no caso parece que não foi gerado um NSU para ela, sabe de quando é?

Tem um tópico onde ocorre algo parecido, ele foi tratado aqui [Documento não localizado #11](https://github.com/lucashpmelo/node-mde/discussions/11). Nele eu explico mais detalhado como o serviço de Distribuição funciona.

**Comment by skerme** [comment]
13230834550453000103550010000028331140906379

2023-08-18T08:54:24-04:00

e está no portal da nfe

**Comment by lucashpmelo** [comment]
Vamos fazer um teste, ao invés de consultar pela chave das notas consulte pelo ultimo NSU. Estou achando que a Sefaz não está gerando novos NSUs para o seu CNPJ.

``` js
const { DistribuicaoDFe } = require("node-mde");
const fs = require("fs");

async function funcao() {
  const distribuicao = new DistribuicaoDFe({
    pfx: fs.readFileSync("./sabor.pfx"),
    passphrase: "Sabor2022",
    cnpj: "48327424000191",
    cUFAutor: "13", // <-- Código do estado do Amazonas
    tpAmb: "1",
  });

  const consulta = await distribuicao.consultaUltNSU('000000000000000');

  if (consulta.error) {
    throw new Error(consulta.error);
  }

  console.log(consulta);
}

console.log("RESULTADO: ", funcao());
```

**Comment by skerme** [comment]
![image](https://github.com/lucashpmelo/node-mde/assets/66704465/5f5f6dac-ae01-433c-a49d-ded360263bb6)

**Comment by lucashpmelo** [comment]
Você fez mais de uma consulta? Essa rejeição ocorre quando é feito uma consulta passando o mesmo NSU repetido, ou fora de ordem no período menor que 1 hora.

No caso como o `maxNSU` retornou como zero, acredito que realmente não estava gerando novos NSUs. Agora como você fez uma consulta a Sefaz irá começar a gerar os NSU para as próximas notas que forem emitidas para você.

**Comment by skerme** [comment]
Muito obrigado. Já estou no aguardo do dono do cnpj me enviar uma nota a
partir de amanhã.

Em dom., 8 de out. de 2023 às 21:13, Lucas Melo ***@***.***>
escreveu:

**Comment by skerme** [comment]
Voltei.
A resposta de hoje foi essa. Parece que hoje foram emitidas 4 notas.
Tem como eu obter as chaves?
![image](https://github.com/lucashpmelo/node-mde/assets/66704465/a4c0cb59-0a9e-46ce-9457-eaa6f1350c01)

**Comment by lucashpmelo** [comment]
Boa noite, você pode obter as informações do XML dentro da propriedade `docZip` que fica dentro da prorpiedade `data`, ela é uma lista de todos Documentos Fiscais retornados.

``` js
 {
   data: {
     tpAmb: '2',
     verAplic: '1.5.11',
     cStat: '138',
     xMotivo: 'Documento(s) localizado(s)',
     dhResp: '2022-06-21T10:48:14-03:00',
     ultNSU: '000000000000050',
     maxNSU: '000000000000212',
     docZip: [
       {
         xml: '<resNFe xmlns:xsd="http://www.w3.org/2001/XMLSchema" ... </resNFe>',
         json: { resNFe: { ... } },
         nsu: '000000000000049',
         schema: 'resNFe_v1.01.xsd',
       },
       {
         xml: '<nfeProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"> ... </nfeProc>',
         json: { nfeProc: { ... } },
         nsu: '000000000000050',
         schema: 'procNFe_v4.00.xsd',
       },
     ],
   },
 }
```

**Comment by skerme** [comment]
Blz. Vou retirar do zip aqui. Valeu.

**Comment by lucashpmelo** [comment]
Boa tarde. Quando o autor que está consultado é o destinatário da NF-e esse serviço sempre irá retornar primeiro na consulta o XML resumido da nota. Para conseguir obter o XML completo é necessário realizar a emissão do Evento de Manifestação do Destinatário que é o MD-e. Você pode fazer isso utilizando essa biblioteca, só consultar a parte de [Manifestação do Destinatário](https://github.com/lucashpmelo/node-mde#manifesta%C3%A7%C3%A3o-do-destinat%C3%A1rio) no README.md.

Depois de manifestar as notas resumidas você pode continuar com a consulta pelo ultimo NSU, que a Sefaz irá gerar novos NSUs agora com o XML completo das NF-e.

**Comment by skerme** [comment]
Obrigado!!!

Em ter., 10 de out. de 2023 às 12:36, Lucas Melo ***@***.***>
escreveu:
