### ISSUE TITLE
Captura e manifestação de CT-e?

### ISSUE THREAD

**Issue by DenisBessa** [lucashpmelo/node-mde#14]
### Descrição

Olá!

Essa biblioteca é excelente! Parabéns!

Gostaria de saber se há alguma possibilidade de captura e manifestação de CT-e também. Procurei na documentação e no código, mas não encontrei nenhuma referência.

Abraços.

**Comment by lucashpmelo** [comment]
Boa tarde, a biblioteca só possui implementando os serviços de Distribuição e Manifestação de NF-e, ela não suporta CT-e.

**Comment by lucashpmelo** [comment]
Fechando a Issue por falta de atividade.
