### ISSUE TITLE
Dúvidas

### ISSUE THREAD

**Issue by Militao36** [lucashpmelo/node-mde#15]
### Descrição

Olá, muito bom a lib gostei bastante. Fiquei apenas com algumas dúvidas

1 - Como sei qual é o NCU para consulta, pois quero saber as notas emitidas contra meu CNPJ, porém não tenho esse número.
2 - Quando eu passar o NCU, ele retorna todas notas do mês/dia/semana ou tudo mesmo?

Obrigado

**Comment by lucashpmelo** [comment]
Boa tarde,

>1 - Como sei qual é o NCU para consulta, pois quero saber as notas emitidas contra meu CNPJ, porém não tenho esse número.

Basta utilizar a [Consulta por ultNSU](https://github.com/lucashpmelo/node-mde?tab=readme-ov-file#consulta-por-ultnsu) passando o NSU `'000000000000000'`, ela irá retornar a relação de notas e o valor do próximo `ultNSU`, após isso basta seguir realizando as consultas utilizando sempre o `ultNSU` da consulta anterior.

>2 - Quando eu passar o NCU, ele retorna todas notas do mês/dia/semana ou tudo mesmo?

É retornado todos os documentos emitidos nos últimos 90 dias, cada consulta por ultNSU retorna no máximo 50 documentos, então você deve ir consultando até o valor do `ultNSU` ser igual ao do `maxNSU`.

**Comment by Militao36** [comment]
Muito obrigado pelo retorno. Estou querendo auxiliar no projeto, chegou a verificar a possibilidade de consultar outros documentos fiscais, não apenas NFe?

**Comment by lucashpmelo** [comment]
>chegou a verificar a possibilidade de consultar outros documentos fiscais, não apenas NFe?

No momento não, eu já considero essa biblioteca pronta, no máximo vou implementar o novo evento de Emitente/Destinatário referente a Transportadora, e também a possibilidade de enviar os eventos com o valor do `nSeqEvento` igual a 2, mas para isso tem que esperar a Sefaz disponibilizar esses novos recursos em ambiente de homologação.

**Comment by Militao36** [comment]
Certo, más hoje na sefaz tem algo de pronto uso para ver as emissões contra meu CNPJ para esses outros documentos fiscais? 
Estava precisando para os demais tbm, ai queria implementar

**Comment by lucashpmelo** [comment]
Quais outros documentos você está falando?

**Comment by Militao36** [comment]
Seria os CTe / MDF-e
