### ISSUE TITLE
NFe completa

### ISSUE THREAD

**Issue by PedroTrogo** [lucashpmelo/node-mde#16]
### Descrição

Olá!
Como fazer o download da nota completa? A consulta só está me retornando um resumo.

**Comment by lucashpmelo** [comment]
Boa tarde,

Quando o autor que está consultado é o destinatário da NF-e esse serviço sempre irá retornar primeiro na consulta o XML resumido da nota. Para conseguir obter o XML completo é necessário realizar a emissão do Evento de Manifestação do Destinatário que é o MD-e. Você pode fazer isso utilizando essa biblioteca, só consultar a parte de [Manifestação do Destinatário](https://github.com/lucashpmelo/node-mde#manifesta%C3%A7%C3%A3o-do-destinat%C3%A1rio) no [README.md](https://github.com/lucashpmelo/node-mde#readme).

Depois de manifestar as notas resumidas você pode continuar com a consulta pelo ultimo NSU, que a Sefaz irá gerar novos NSUs agora com o XML completo das NF-e.

Para entender o que cada evento significa e os prazos para emissão dos mesmos, você deve consultar a [Nota Técnica 2020.001](https://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=nPKQWFVzvQo=).

**Comment by PedroTrogo** [comment]
Entendi. Muito obrigado pelo esclarecimento!
