### ISSUE TITLE
Consulta por Chave não está retornando nsu

### ISSUE THREAD

**Issue by WesleyjanLacerda** [lucashpmelo/node-mde#19]
### Descrição

Olá, estou tendo uma situação, que ainda não consegui identificar se é o meu código ou algo relacionado ao repositório, vou compartilhar parte do meu código:

    const consulta = await distribuicao.consultaChNFe(chaveNFe);
    if (consulta.error) {
      return { error: consulta.error };
    }
    const docZip = consulta.data.docZip;
    if (!docZip || docZip.length === 0) {
      //return { error: 'Nenhum documento encontrado.' };
      return { tpAmb, verAplic, cStat, status, ultNSU, maxNSU, message: xMotivo, documentos };
    }
    
    for (const doc of docZip) {
        console.log('nsu: ' + doc.nsu);
        const docInfo = {
          nsu: doc.nsu,
          xml: '', 
          tipo: '', 
          informacoes: {},
        };`
        
Por algum motivo, as vezes no "nsu" retornado da consulta está vindo vazio ou undefined:

![image](https://github.com/user-attachments/assets/fc00fd09-fcc2-486a-b880-ede86292821d)

Não consegui identificar o que pode ser por hora, mas no caso coloquei um tratamento meio "tabajara" para contornar, se alguém puder me ajudar nessa parte, desde já muito obrigado! 

### Exemplo de reprodução

const consulta = await distribuicao.consultaChNFe(chaveNFe);
if (consulta.error) {
  return { error: consulta.error };
}
const docZip = consulta.data.docZip;
if (!docZip || docZip.length === 0) {
  //return { error: 'Nenhum documento encontrado.' };
  return { tpAmb, verAplic, cStat, status, ultNSU, maxNSU, message: xMotivo, documentos };
}

for (const doc of docZip) {
    console.log('nsu: ' + doc.nsu);
    const docInfo = {
      nsu: doc.nsu,
      xml: '', 
      tipo: '', 
      informacoes: {},
    };`

**Comment by lucashpmelo** [comment]
Isso ocorre com chaves especificas ou é aleatório?

Quando ocorrer esse caso salve o XML de retorno da Sefaz para facilitar o debug:

```js
console.log(consulta.resXml)
```

**Comment by WesleyjanLacerda** [comment]
[202409251623543ch.json](https://github.com/user-attachments/files/17138848/202409251623543ch.json)
[202409251623370ch.json](https://github.com/user-attachments/files/17138849/202409251623370ch.json)


Eu armazeno o xml, mas pegando do result da requisição, eu não cheguei colocar para armazeno o resXml ou o reqXml

**Comment by lucashpmelo** [comment]
> será será está "muito rápido" de uma requisição a outra, não dando tempo para o web service da sefaz gerar o nsu e dar o retorno logo em seguida pela a consulta por chave ?

Realmente parece que é esse o caso, pois o retorno está vindo sem o NSU na Tag `docZip`.

Eu sempre recomendo esperar uns 30~60 segundos depois de manifestar para consultar a nota completa, pois em horários de pico a sincronização entre a Sefaz do estado com o Ambiente Nacional pode demorar um pouco.

Você poderia tentar alterar o seu fluxo talvez, primeiro faz o manifesto de todas notas resumidas e depois consulta as notas, assim vai dando tempo da Sefaz sincronizar elas por trás.

**Comment by WesleyjanLacerda** [comment]
Entendi, imaginei que seria isso, as vezes acho que a "sefaz não quer colaborar comigo rs..." 

Vou mudar a lógica aqui, e fazer o teste, no caso seria:
- Manifestar "todas as nf - resumo"
- Baixar o xml por chave. 

Seria isso mesmo ?

**Comment by lucashpmelo** [comment]
Se você tiver muitas notas para consultar seria melhor usar o método de consulta por Ultimo NSU (`ultNSU`) para receber os XML completos das notas manifestadas. As consultas por Chave ou NSU especifico tem um limite de 20 requisições por hora, se passar do limite toma consumo indevido.

Mas a ideia é essa mesmo que você escreveu, o importante é só esperar alguns segundos entre o manifesto e a nova consulta para garantir que a Sefaz sincronizou a nota do lado dela.

**Comment by lucashpmelo** [comment]
Fechando a Issue por falta de atividade.
